name = evolve
title = Evolve
description = Admin-only tools for terraforming, structures, villages, treasures, and server events.
depends = mcl_core, mcl_chests, mcl_loot
optional_depends = mcl_structures, mcl_villages, mcl_mobs, mobs_mc, mcl_farming, mcl_doors, mcl_beds
